/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.receitas;

import com.mycompany.dao.DaoReceitas;
import com.mycompany.modelo.ModDespesas;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
/**
 *
 * @author marcella.1963
 */
public class ListReceitas extends javax.swing.JFrame {

    /**
     * Creates new form ListReceita
     */
    public ListReceitas() {
        initComponents();
        setLocationRelativeTo(null);
        
        listarTodos();
    }
    public void listarTodos(){
        try{
            DefaultTableModel defaultTableModel = (DefaultTableModel)TableReceita.getModel();
    
            TableReceita.setModel(defaultTableModel);
            
            DaoReceitas daoReceitas = new DaoReceitas();
    
            ResultSet resultSet = daoReceitas.ListarTodos();
        
             defaultTableModel.setRowCount(0);
            while(resultSet.next()){
                String id = resultSet.getString(1);
                String categoria_id = resultSet.getString(2);
                String nome = resultSet.getString(3);
                Double valor = resultSet.getDouble(4);
                String data_de_lançamento = resultSet.getString(5);
                

                defaultTableModel.addRow(new Object[]{id, categoria_id, nome, valor, data_de_lançamento});
            }
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }
        // public void listarPorId(int pID){
       //try{
       // DefaultTableModel defaultTableModel = (DefaultTableModel) Table.getModel();
        
       // TableDespesas.setModel(defaultTableModel);
        
        //DaoDespesas daoDespesas = new DaoDespesas();
        
       // ResultSet resultSet = daoDespesas.listarPorId(pID);
        
       // defaultTableModel.setRowCount(0);
        
       // while(resultSet.next()){
        //    String id = resultSet.getNString(1);
           // String categoria_id = resultSet.getNString(2);
           /* String despesa = resultSet.getNString(3);
            Double valor = resultSet.getDouble(4);
            String vencimento = resultSet.getNString(5);
            String pagamento = resultSet.getNString(6);
            
            defaultTableModel.addRow(new Object[]{id,categoria_id, despesa, valor, vencimento, pagamento});
        }
        
    }catch(Exception e ){
        System.out.println(e.getMessage());
    
        }
    }
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfFiltrar1 = new javax.swing.JComboBox<>();
        jtfTextField1 = new javax.swing.JTextField();
        jtfButtonBuscar1 = new javax.swing.JButton();
        jtfLabelRegistro1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableReceita = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtfFiltrar1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "ID", "Nome", "Descrição" }));

        jtfButtonBuscar1.setText("Buscar");

        jtfLabelRegistro1.setText("Dê dois cliques no registro para editá-lo");

        TableReceita.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Categoria", "Despesa", "Valor", "Data de lançamento"
            }
        ));
        TableReceita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableReceitaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TableReceita);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtfFiltrar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfTextField1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfButtonBuscar1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jtfLabelRegistro1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfFiltrar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfButtonBuscar1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfLabelRegistro1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TableReceitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableReceitaMouseClicked
    if(evt.getClickCount() ==2){
    
    }
    
    }//GEN-LAST:event_TableReceitaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListReceitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListReceitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListReceitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListReceitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListReceitas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableReceita;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jtfButtonBuscar1;
    private javax.swing.JComboBox<String> jtfFiltrar1;
    private javax.swing.JLabel jtfLabelRegistro1;
    private javax.swing.JTextField jtfTextField1;
    // End of variables declaration//GEN-END:variables
}
